### ISSUE TITLE
Angular and Styles

### ISSUE THREAD

**Issue by cheng93** [webpack-contrib/raw-loader#77]
* Operating System: Windows 10
* Node Version: 10.15.1
* NPM Version: 6.7.0
* webpack Version: see below
* raw-loader Version: see below

### Expected Behavior

webpack is successful

### Actual Behavior

webpack is not successful

### Code

webpack and raw-loader version are in repo

https://github.com/cheng93/raw-loader-issue

```
ERROR in Expected 'styles' to be an array of strings.

10 silly lifecycle raw-loader-issue@1.0.0~build: Args: [ '/d /s /c', 'webpack --mode=development' ]
11 silly lifecycle raw-loader-issue@1.0.0~build: Returned: code: 2  signal: null
12 info lifecycle raw-loader-issue@1.0.0~build: Failed to exec build script
13 verbose stack Error: raw-loader-issue@1.0.0 build: `webpack --mode=development`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\dev\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid raw-loader-issue@1.0.0
15 verbose cwd C:\code\cheng93\raw-loader-issue
16 verbose Windows_NT 10.0.17763
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\dev\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v10.15.1
19 verbose npm  v6.7.0
20 error code ELIFECYCLE
21 error errno 2
22 error raw-loader-issue@1.0.0 build: `webpack --mode=development`
22 error Exit status 2
23 error Failed at the raw-loader-issue@1.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]
```

**Comment by evilebottnawi** [comment]
Please open issue in `@ngtools/webpack`, we start migrate on `import`/`export` in some loaders/plugins, so it should be fixed in other plugins/loaders too, we can't do something on our side

**Comment by thw0rted** [comment]
This actually isn't limited to the CLI, it impacts both the dynamic and AOT compilers.  I'll try to put together a simple repro for an Angular issue tomorrow.  I'm worried that I'm doing something wrong, though, since raw-loader v2 has been out for months and I don't see that much discussion of the problem.
